### ISSUE TITLE
[Suggestion] Add GitHub repo link in VSCode extension home page.

### ISSUE THREAD

**Issue by tcztzy** [ninoseki/vscode-pylens#3]
![image](https://user-images.githubusercontent.com/12420478/83243785-f7bf4b80-a1d0-11ea-8373-2c9c989c5260.png)
Good job! Seems like I am the first user of this extension.

**Comment by ninoseki** [comment]
@tcztzy There is a link already.

<img width="338" alt="Screen Shot 2020-05-29 at 6 32 58 PM" src="https://user-images.githubusercontent.com/291028/83244881-f09d3b00-a1da-11ea-82c3-06dae82531f6.png">

**Comment by tcztzy** [comment]
![image](https://user-images.githubusercontent.com/12420478/83245722-b5e3d480-a1d3-11ea-96ce-64152c03c9fe.png)
I mean this page
