### ISSUE TITLE
Support flit

### ISSUE THREAD

**Issue by hmvp** [ninoseki/vscode-pylens#81]
The description says it supports pyproject.toml but actually it supports only poetry. However Flit (https://flit.readthedocs.io/en/latest/) also uses pyproject.toml but with different keys.

It would be nice if that is also supported..

**Comment by ninoseki** [comment]
Thank you for the suggestion. 
I implemented a support for Flit in #83. 
But the current implementation is very naive and it may miss something.  Please let me know if you find something wrong.
