### ISSUE TITLE
Support for "Compatible release" and additionnal version specifiers

### ISSUE THREAD

**Issue by PhilMacKay** [ninoseki/vscode-pylens#93]
Hi, thanks for the good work on the extension, it saved me a lot of time maintaining our team's dependencies!

I recently found myself using more and more the "Compatible release" version specifier `~=`, as documented here: https://peps.python.org/pep-0440/#version-specifiers

I noticed it doesn't seem to be detected and pylens doesn't display the latest version.
Of all the version specifier, it's the one I find most useful, but I went and checked for the other ones listed in PEP 440, and I noticed some other ones were not supported either.

Here are my observations, tested in a "requirement.txt" file, but they seem to hold the same in `pyproject.toml`.

```
mypy ~= 0.961  # Not detected
mypy == 0.961
mypy != 0.961  # Not detected
mypy <= 0.961  # Not detected
mypy >= 0.961
mypy < 0.961   # Not detected
mypy > 0.961
mypy === 0.961
```

According to PEP 440 and 508 (see Grammar here: https://peps.python.org/pep-0508/#grammar), they are the only operators defined, so it should be safe to assume that they cover every possible case unless a new PEP is released.

**Comment by ninoseki** [comment]
Thanks for the heads-up.
I updated the implementation and released a new version (0.1.3).
