### ISSUE TITLE
Add support to `*-requirements.txt` pattern

### ISSUE THREAD

**Issue by isquicha** [ninoseki/vscode-pylens#99]
Currently the extension supports finding a lot of requirements files, such as development and testing dependencies, with the `requirements-*.txt` pattern, for example `requirements-dev.txt`, but not for something like `dev-requirements.txt`.

**Comment by isquicha** [comment]
@ninoseki I don't know if it wast intentional, but changes in #100 were reverted on a5fa05bf775e3244fd84abf4049d68f8e2b7d0ce
This issue should be reopened 😃

**Comment by ninoseki** [comment]
It's totally my fault. I will fix the issue soon.

**Comment by ninoseki** [comment]
Sorry for being late. The patch (#105) is included in the latest release. (v0.1.16)
